### PR TITLE
Add netusb_camera_driver package

### PR DESCRIPTION
**Pull request by furushchev**
This PR adds driver package for NETUSB camera.

- [x] added nodes / launches
- [x] auto driver installation
- [x] tested with real camera

### CODE REVIEW

**Comment by k-okada** [comment]
Why you have to use this camera? Do you agave up using Linux box on the
robot?

2016年6月12日日曜日、Furushchev<notifications@github.com>さんは書きました:

> This PR adds driver package for NETUSB camera.
> Please do not merge until all features are tested.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/start-jsk/jsk_mbzirc/pull/85
> Commit Summary
>
>    - add netusb_camera_driver package
>    - add netusb_camera_driver to meta package run_depend
>
> File Changes
>
>    - *M* jsk_mbzirc/package.xml
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-0> (1)
>    - *A* netusb_camera_driver/CMakeLists.txt
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-1> (58)
>    - *A* netusb_camera_driver/cfg/NETUSBCamera.cfg
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-2> (32)
>    - *A* netusb_camera_driver/cmake/FindOrDownloadNETUSBCAM.cmake
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-3> (47)
>    - *A* netusb_camera_driver/cmake/download_netusbcam.py
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-4> (58)
>    - *A* netusb_camera_driver/cmake/patch_libudev_symlink.py
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-5> (39)
>    - *A* netusb_camera_driver/include/netusb_camera_driver/NETUSBCamera.h
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-6> (36)
>    - *A* netusb_camera_driver/include/netusb_camera_driver/exceptions.h
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-7> (32)
>    - *A*
>    netusb_camera_driver/include/netusb_camera_driver/netusb_camera_nodelet.h
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-8> (57)
>    - *A* netusb_camera_driver/launch/camera.launch
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-9> (19)
>    - *A* netusb_camera_driver/nodelet_plugins.xml
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-10> (7)
>    - *A* netusb_camera_driver/package.xml
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-11> (31)
>    - *A* netusb_camera_driver/src/NETUSBCamera.cpp
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-12> (122)
>    - *A* netusb_camera_driver/src/netusb_camera_node.cpp
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-13> (23)
>    - *A* netusb_camera_driver/src/netusb_camera_nodelet.cpp
>    <https://github.com/start-jsk/jsk_mbzirc/pull/85/files#diff-14> (178)
>
> Patch Links:
>
>    - https://github.com/start-jsk/jsk_mbzirc/pull/85.patch
>    - https://github.com/start-jsk/jsk_mbzirc/pull/85.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/start-jsk/jsk_mbzirc/pull/85>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3NwuNvQPOmCtZR3bUuCwpBaHbw6Fks5qK6nmgaJpZM4IzuHi>
> .
>


-- 
--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada Sorry, I don't know about linux box.
If I understand @tongtybj 's word correctly, this is very wide fisheye camera for task1 and 3 to view the around course from drone.

**Comment by tongtybj** [comment]
@k-okada 
The NETUSB camera has following features:
1. boardtype (< 10g)
2. UXGA(1600 x 1200)
3. Global Shutter
4. Fisheye
Please see "BC4203CU" in http://www.mvision.co.jp/index_net.html

**Comment by k-okada** [comment]
do you need netusb protocol? or fisheye camera? if you need fisheye camera,
please make a list for candidates

--
◉ Kei Okada

**Comment by tongtybj** [comment]
@k-okada 
- netusb is one of the candidates we are testing.

- fisheye is necessary, because we need very big FOV in the finally landing porces. Please check video in https://drive.google.com/open?id=0BwphddqBjVJ_RnYzSjh5WHJKMWc
- other important criteria for on-board camera:
 1. board-type => light
 2. global shutter => guarantee  image quality when uav vibrates strongly.
 3. fisheye => reason above
 4. enough resolution => testing 1600 x 1200

- Canditates:

1. Net Camera(netusb)
 BC4203CU, http://www.mvision.co.jp/index_net.html
2. IDS UI-3251LE, https://jp.ids-imaging.com/store/produkte/kameras/ui-3251le.html

Both camera are able to attach fisheye lens.

**Comment by k-okada** [comment]
if you need fisheye, you do not need gimbal, is it correct?

--
◉ Kei Okada

**Comment by tongtybj** [comment]
#82

**Comment by tongtybj** [comment]
@furushchev 
I got following error when building the package:

```
Warnings   << netusb_camera_driver:cmake /home/leus/ros/catkin_ws/logs/netusb_camera_driver/build.cmake.000.log
INFO:root:Downloading driver
INFO:root:Unarchiving tarball
INFO:root:Copying library
INFO:root:Copying header files
INFO:root:Finding libudev.so.0
Traceback (most recent call last):
  File "/home/leus/ros/catkin_ws/src/jsk_mbzirc/netusb_camera_driver/cmake/patch_libudev_symlink.py", line 35, in <module>
    if os.path.islink(fpath):
NameError: name 'fpath' is not defined
cd /home/leus/ros/catkin_ws/build/netusb_camera_driver; catkin build --get-env netusb_camera_driver | catkin env -si  /usr/bin/cmake /home/leus/ros/catkin_ws/src/jsk_mbzirc/netusb_camera_driver --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/leus/ros/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/leus/ros/catkin_ws/install; cd -
.....................................................................................................
Finished  <<< netusb_camera_driver                   [ 21.2 seconds ]                                
[build] Summary: All 8 packages succeeded!                                                           
[build]   Ignored:   13 packages were skipped or are blacklisted.                                    
[build]   Warnings:  2 packages succeeded with warnings.                                             
[build]   Abandoned: None.                                                                           
[build]   Failed:    None.                                                                           
[build] Runtime: 21.5 seconds total.                                                                 
[build] Note: Workspace packages have changed, please re-source setup files to use them.
```

Is it OK?

**Comment by furushchev** [comment]
failed because https://github.com/start-jsk/jsk_mbzirc/pull/88 is not merged

**Comment by tongtybj** [comment]
@furushchev 

古田くん、RGBの件は何か進展はあった？

**Comment by furushchev** [comment]
@tongtybj waiting for mail reply...

**Comment by tongtybj** [comment]
@furushchev 

oh...

**Comment by furushchev** [comment]
@tongtybj replies have arrived. I'm now discussing by email.

**Comment by tongtybj** [comment]
@furushchev 
wonderful!

**Comment by furushchev** [comment]
Now data from driver in RGB mode is broken

screenshot from 2016-07-21 18 39 58

So in launch file, RAW data is used (I found that raw data is Bayer GRBG Image) and debayered to RGB.

image

**Comment by furushchev** [comment]
Now I'm discussing to manufacturer by email.

And now I think its ok to merge. @k-okada

**Comment by k-okada** [comment]
i do not think we have time to maintain new driver, please consider using different camera.

**Comment by tongtybj** [comment]
@k-okada 

"diffrent camera" means using the device we have already developed?like prosilica?

**Comment by k-okada** [comment]
yes
"diffrent camera" -> "different camera"
and I know prosillica is too heavy

## 

◉ Kei Okada

**Comment by tongtybj** [comment]
@k-okada 
So how about this
https://www.ptgrey.com/chameleon3-usb3-vision-cameras
Are "we" familiar with this device?

**Comment by k-okada** [comment]
http://wiki.ros.org/pointgrey_camera_driver

## 

◉ Kei Okada

**Pull request merged**
