### PR TITLE
[WIP] try to create launch/jsk_mbzirc_task_3.launch

### PR DESCRIPTION
**Pull request by haraduka**
I can display three uavs to gazebo and can operate each uav by teleop.
But I cannot display models to rviz and some errors occur at rviz.
please tell me why.

### CODE REVIEW

**Comment by k-okada** [comment]
please check https://github.com/haraduka/jsk_mbzirc/pull/1, you need to configure rviz setttings to show the robts, they have different tf structure that task1, you can use `rosrun tf view_frames` to see current tf sttructure.

**Comment by k-okada** [comment]
@haraduka 何か進捗あったかな？

**Comment by haraduka** [comment]
ごめんなさい何もしてないです…

**Comment by furushchev** [comment]
overtaken by https://github.com/start-jsk/jsk_mbzirc/pull/76

**Pull request closed without merging**
