### PR TITLE
Add real hex-rotor uav robot model which will be used in MBZIRC.

### PR DESCRIPTION
**Pull request by tongtybj**
- [ ] [jsk_mbzirc_tasks/urdf/meshes/tarrot680_p.stl,  jsk_mbzirc_tasks/urdf/uav.urdf.xacro] 
  Add real uav model which is hexrotor(TARROT680)
- [ ] [jsk_mbzirc_tasks/launch/jsk_mbzirc_task_1.launch, jsk_mbzirc_tasks/launch/jsk_mbzirc_task_3.launch] 
Fix: change the robot description argument.

### CODE REVIEW

**Comment by tongtybj** [comment]
Created uav model using Solid Edge(.stl file). This is the real model with actual specification.

**Comment by k-okada** [comment]
please name your robot

--
◉ Kei Okada

**Comment by tongtybj** [comment]
How about "black swift"

2016/06/13 9:14、Kei Okada <notifications@github.com> のメッセージ:

> please name your robot
> 
> --
> ◉ Kei Okada
> 
>

**Comment by cretaceous-creature** [comment]
how about "swift elf"  "swift puck"....
Maybe the last version is not black.......

Personally I dont like black robots as same lasers cant
detect the black surface, just like black cars in autonomous driving..

2016-06-13 12:09 GMT+09:00 趙 漠居 <notifications@github.com>:

> How about "black swift"
>
> 2016/06/13 9:14、Kei Okada <notifications@github.com> のメッセージ:
>
> > please name your robot
> >
> > --
> > ◉ Kei Okada
> >
> >

**Comment by tongtybj** [comment]
Give a name called "hawk":
jsk_mbzirc_tasks/urdf/uav.urdf.xacro → jsk_mbzirc_tasks/urdf/hawk.urdf.xacro

**Comment by tongtybj** [comment]
@k-okada 

Please merge if it is ok

**Pull request merged**
