### PR TITLE
Add mission failure rule for UAV

### PR DESCRIPTION
**Pull request by tongtybj**
This PR  is separated from commit in #65, and was also discussed in #62 

- [ ] [jsk_mbzirc_tasks/include/jsk_mbzirc_tasks/mbzirc_gazebo_uav_collision_rule_plugin.h, jsk_mbzirc_tasks/src/mbzirc_gazebo_uav_collision_rule_plugin.cpp] 
Add feature:  check whether hitting ground
  - Use rayshape and collisionbox to check the distance between and ground. If the distance is too short(e.g. <.01m), motors will shutdown.

### CODE REVIEW

**Comment by k-okada** [comment]
> If the distance is too short(e.g. <.01m), motors will shutdown.

is this the definition of mission failure rule?

**Comment by tongtybj** [comment]
This is, but it is designed by myself. There is no specific description about the failure rule in regulation

**Comment by k-okada** [comment]
does this this plugin work with plugin for https://github.com/start-jsk/jsk_mbzirc/blob/master/jsk_mbzirc_common/src/mbzirc_gazebo_truck_plugin.cpp#L194
Are you assuming when robot complete the task1, the robots stops at 1.0? above the truck and it not satisfy "failure rune"?

**Comment by tongtybj** [comment]
I just check the distance(rayshape) between uav and ground(arena):
https://github.com/tongtybj/jsk_mbzirc/blob/a1254ad5c06df37fa9edc79aa647892d63a46059/jsk_mbzirc_tasks/src/mbzirc_gazebo_uav_collision_rule_plugin.cpp#L112

So, this is not conflict with the mission complete rule in 
 https://github.com/start-jsk/jsk_mbzirc/blob/master/jsk_mbzirc_common/src/mbzirc_gazebo_truck_plugin.cpp#L194

Beside, I have checked with cheat mode, there is no problem.

**Comment by k-okada** [comment]
so, so last question is why you put this within jsk_mbzirc_tasks, not jsk_mbzirc_common.

**Comment by tongtybj** [comment]
I was considering jsk_mbzirc_common is for the elements about the environment of the competition, like arena, truck, objects, but not uav or ugv. So I put this in jsk_mbzirc_tasks. Which should be better?

**Comment by k-okada** [comment]
ok, so put it in tasks, please fix commit to pass travis

**Comment by tongtybj** [comment]
@furushchev 
It seems like task2 test failed, and I can not figure out the reason:
 
```                                                                                                             
[ROSTEST]-----------------------------------------------------------------------                                                       
[jsk_mbzirc_tasks.rosunit-remaining_time_test/test_hz][passed]                  
SUMMARY                                                                         
 * RESULT: FAIL                                                                 
 * TESTS: 1                                                                     
* ERRORS: 1                                                                    
 * FAILURES: 0    
```

**Comment by furushchev** [comment]
task2 test failed even after 10 times retry.
restarted travis for further debugging.

**Comment by tongtybj** [comment]
finally passed.

@k-okada 
Please merge if it is ok

**Comment by k-okada** [comment]
Conflicting

**Comment by tongtybj** [comment]
@k-okada 
Fix conflict.
Please merge

**Pull request merged**
